### ISSUE TITLE
Mock up perfWrite() method

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/epitelete#15]
When we 'close the circle' the editor should send back HTML which eventually turns into PERF which can then be written back to the cache.

The method should take
- the document bookCode and
- PERF fragment for a sequence

as its arguments, and should assign that JSON to the appropriate place in `documents` before returning the amended `documents` object. The bookCode and sequenceId must already exist since, at present, we don't expect the editor to create new sequences or indeed documents this way.

Before assignment the method should validate the PERF. I just realised that I need to rework the validator for this use case... but, when we have the validator, the workflow will be
- assemble the modified document
- validate that document
- if it validates, update `this.documents`
- otherwise throw an error

**Comment by mvahowe** [comment]
Validator is at https://www.npmjs.com/package/proskomma-json-validator - I designed it to validate at 4 different levels, so I think you could validate the sequence PERF in isolation before adding it to `this.document`. There are sample documents in the test directory of the repo for that module, to test writing of a valid sequence, and you could break that JSON to test not writing an invalid sequence.

**Comment by mandolyte** [comment]
On handling deletion and addition of sequences...

Suppose we followed the following rules:
- if the value for a sequence is the empty string, then remove it from the PERF
- if the value for a sequence Id does not exist in the PERF, then add it.

Both these would need to be done prior to validation.
