### ISSUE TITLE
A naive implementation of undo/redo

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/epitelete#18]
### Discussed in https://github.com/Proskomma/epitelete/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **mvahowe** May 23, 2022</sup>
Modern editors typically often multi-step undo/redo functionality. Epitelete should provide this at the level of write operations (which may represent a lot of editor keystrokes).

It should be possible to implement this naively with no dependencies. This enables us to build out and test the API. If scalability becomes an issue we can refactor the internals to use deltas (or whatever), without changing the API used by consuming editors.

Right now we have an object containing documents. One naive approach would be to store an array of documents for each bookCode. We'd then need to consider things like
- what's the maximum number of items we store before we start throwing away the oldest one?
- how do we track which item is the 'current' one for read operations?

</div>

**Comment by mandolyte** [comment]
Some thoughts... it looks like PERF will manage things at the sequence level. The writePerf() method will know both the previous value for a sequence and the updated value for a sequence. So one way would be to keep an array in the Epitelete class onto which the updated sequence values are pushed. The sequence could be wrapped in some metadata. For example:
```
{
  editnumber: int, -- position in this array
  bookCode: book_code_value,
  timestamp: tstamp, -- when the value was pushed into this array
  sequence: previous_sequence_value,
}
```

Then some methods could be used to search for and return matches (probably in LIFO order?); reset/empty the array; return all of it; &c.

**Comment by mvahowe** [comment]
> So one way would be to keep an array in the Epitelete class onto which the updated sequence values are pushed.

That feels to me like a good approach at this point in the project lifecycle. Maybe we'll need something more elegant or efficient at some point, but it would be good to get something working, and that everyone understands, quickly, and then to see if the functionality gives users and devs what they need.

I'd be inclined to go for one stack per document because, as mentioned elsewhere, editing one sequence may change other sequences, or even make other sequences appear or disappear. If we start undoing and redoing sequences independently I think we'll end up with integrity issues. (Note that all these sequences together are the equivalent of USFMJS for one document, ie we're not in the realm of Big Data here.)

If we use an array as a stack, I think all we need is a pointer to the current document object in that array. If we push onto the left of that array, ie the most recent value is at index 0:

- __writePerf()__ pushes a new value onto that stack, sets the pointer to 0, and optionally drops the oldest value if the stack has reached its size limit
- __undo()__ increments the pointer, to point at the next document object down, assuming there is one of those
- __redo()__ decrements the pointer, to point at the next document object up, assuming that we're not already on the most recent document

Adding a timestamp to the sequence could be nice. We could probably make that option in the PERF, to avoid inventing another data structure that needs to be documented and validated.
