### ISSUE TITLE
Stop committing package-lock.json?

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/epitelete#41]
@abelpz and I appear to be playing package-lock ping pong. I think the way it works is that Abel's system adds (most recently) 6881 lines to that file, and then mine takes it out. This is making for huge, uninteresting diffs and, also, if there's that much difference between 2 systems, and yet both systems still work, how useful can the content of this file be?

@klappy Can you think of a reason not to `ignore` this file?

**Comment by klappy** [comment]
I’d say for now, ignore that file and try yarn to see if it is consistent between your systems. It’s worth a shot.

**Comment by abelpz** [comment]
For what I've read so far it seems like yarn.lock is consistent between systems. I made the change to yarn, let's try that.
